// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCbtiyQUTK_RAbCyvUA6jsa6Xto2bYQjM',
    appId: '1:963559316894:web:5808aa8cef20ac207b4a8f',
    messagingSenderId: '963559316894',
    projectId: 'fruits-d427c',
    authDomain: 'fruits-d427c.firebaseapp.com',
    storageBucket: 'fruits-d427c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVz39zBc_CPvb27EGqtWzvdEZZDNW_08',
    appId: '1:963559316894:android:c60206bd3feb06707b4a8f',
    messagingSenderId: '963559316894',
    projectId: 'fruits-d427c',
    storageBucket: 'fruits-d427c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyksoRBHBlL_tmnF0eIiYuQNbSB5G_OY',
    appId: '1:963559316894:ios:d63a867067da9e947b4a8f',
    messagingSenderId: '963559316894',
    projectId: 'fruits-d427c',
    storageBucket: 'fruits-d427c.appspot.com',
    iosBundleId: 'com.example.fruitsmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyksoRBHBlL_tmnF0eIiYuQNbSB5G_OY',
    appId: '1:963559316894:ios:f464af8a673088927b4a8f',
    messagingSenderId: '963559316894',
    projectId: 'fruits-d427c',
    storageBucket: 'fruits-d427c.appspot.com',
    iosBundleId: 'com.example.fruitsmarket.RunnerTests',
  );
}
